steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: gcr.io/cloud-builders/gsutil
  args: ['-m','rsync','-r','composer/dags','gs://${_GCS_BUCKET}/dags']
- name: gcr.io/cloud-builders/gsutil
  args: ['-m','rsync','-r','composer/plugins','gs://${_GCS_BUCKET}/plugins']
- name: gcr.io/cloud-builders/gsutil
  args: ['-m','rsync','-r','composer/data','gs://${_GCS_BUCKET}/data']
  